Project/Models/Complaint.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Models
{
    public class Complaint
    {
        public int Id { get; set; }
        [StringLength(20, MinimumLength = 4)]
        [Required(ErrorMessage ="The Category field is requied")]
        public string ComplaintName { get; set; }
        [StringLength(15, MinimumLength = 4)]
        [Required(ErrorMessage = "The Location field is requied")]
        public string LocationComplaint { get; set; }
        [StringLength(60,MinimumLength =7)]
        [Required(ErrorMessage = "The Description field is requied")]
        public string DescriptionComplaint { get; set; }
        [Required]
        public string Path { get; set; }

    

       
    }

}

Project/ViewModels/ComplaintViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Project.ViewModels
{
    public class ComplaintViewModel
    {
        public int Id { get; set; }
   
        public string ComplaintName { get; set; }

        public string LocationComplaint { get; set; }

        public string DescriptionComplaint { get; set; }


        public IFormFile Path { get; set; }
    }
}

Project/Controllers/ComplaintsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
    public class ComplaintsController : Controller
    {
        private readonly ComplaintsUserContext _context;
        private readonly UserManager<IdentityUser> userManager;
        private readonly GetUserIdContext _con;

        public ComplaintsController(ComplaintsUserContext context, UserManager<IdentityUser> userManager,GetUserIdContext con)
        {
            _context = context;
            this.userManager = userManager;
            _con = con;
        }

       
        [Authorize(Roles = "Admin")]
        // GET: Complaints
        public async Task<IActionResult> Index(string searchName, string searchString)
        {
            IQueryable<string> genderQuery = from m in _context.Complaint
                                             orderby m.ComplaintName
                                             select m.ComplaintName;
            var complaints = from m in _context.Complaint
                           select m;

            var userId = userManager.GetUserId(HttpContext.User);
           

          

            if (!string.IsNullOrEmpty(searchString))
            {
                complaints = complaints.Where(s => s.LocationComplaint.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(searchName))
            {
                complaints = complaints.Where(x => x.ComplaintName == searchName);
            }

            var ComplaintGenderListM = new GenderListModel
            {
                 user = userManager.FindByIdAsync(userId).Result,
            ComplaintName = new SelectList(await genderQuery.Distinct().ToListAsync()),
                Complaints = await complaints.ToListAsync()
     
          
        };

            return View(ComplaintGenderListM);
        }

        // GET: Complaints/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaint
                .FirstOrDefaultAsync(m => m.Id == id);
            if (complaint == null)
            {
                return NotFound();
            }

            return View(complaint);
        }

        public IActionResult SaveRecord(GetUserId user)
        {
            ApplicationUser app = new ApplicationUser();

            GetUserId comp1 = new GetUserId();
            comp1.UserId = userManager.GetUserId(HttpContext.User);

            _con.GetUserId.Add(comp1);
            _con.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Complaints/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Complaints/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ComplaintName,LocationComplaint,DescriptionComplaint,Path")] Complaint complaint)
        {
            ApplicationUser app = new ApplicationUser();
         
            if (ModelState.IsValid)
            {
                _context.Add(complaint);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(complaint);
        }

        // GET: Complaints/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaint.FindAsync(id);
            if (complaint == null)
            {
                return NotFound();
            }
            return View(complaint);
        }

        // POST: Complaints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ComplaintName,LocationComplaint,DescriptionComplaint,path")] Complaint complaint)
        {
            if (id != complaint.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(complaint);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComplaintExists(complaint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(complaint);
        }

        // GET: Complaints/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaint
                .FirstOrDefaultAsync(m => m.Id == id);
            if (complaint == null)
            {
                return NotFound();
            }

            return View(complaint);
        }

        // POST: Complaints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var complaint = await _context.Complaint.FindAsync(id);
            _context.Complaint.Remove(complaint);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComplaintExists(int id)
        {
            return _context.Complaint.Any(e => e.Id == id);
        }
    }
}

Project/Views/Complaints/Create.cshtml
@model Project.Models.Complaint

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Complaint</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ComplaintName" class="control-label">Category</label>
               <input asp-for="ComplaintName" class="form-control" />
                <span asp-validation-for="ComplaintName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationComplaint" class="control-label">Location</label>
                <input asp-for="LocationComplaint" class="form-control" />
                <span asp-validation-for="LocationComplaint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionComplaint" class="control-label">Description</label>
                <input asp-for="DescriptionComplaint" class="form-control" />
                <span asp-validation-for="DescriptionComplaint" class="text-danger"></span>
            </div>
      
<div class="form-group">  
      <label asp-for="Path" >Document</label>
    <input type="file"  name="path"> 
                        </div>  
      
     

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            </form>
   
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts{  
    <script type="text/javascript">  
        // Add the following code if you want the name of the file appear on select  
        $(".custom-file-input").on("change", function () {  
            var fileName = $(this).val().split("\\").pop();  
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);  
        });  
    </script>  
}  

Project/Views/Complaints/Delete.cshtml
@model Project.Models.Complaint

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Complaint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComplaintName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComplaintName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationComplaint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationComplaint)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionComplaint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionComplaint)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Project/Views/Complaints/Details.cshtml
@model Project.Models.Complaint

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Complaint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComplaintName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComplaintName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationComplaint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationComplaint)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionComplaint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionComplaint)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Project/Views/Complaints/Edit.cshtml
@model Project.Models.Complaint

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Complaint</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ComplaintName" class="control-label"></label>
                <input asp-for="ComplaintName" class="form-control" />
                <span asp-validation-for="ComplaintName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationComplaint" class="control-label"></label>
                <input asp-for="LocationComplaint" class="form-control" />
                <span asp-validation-for="LocationComplaint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionComplaint" class="control-label"></label>
                <input asp-for="DescriptionComplaint" class="form-control" />
                <span asp-validation-for="DescriptionComplaint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Project/Views/Complaints/Index.cshtml
@model Project.Models.GenderListModel


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Complaints" asp-action="Index" method="get">
<p>
    Select Category: <select asp-for="SearchName" asp-items="Model.ComplaintName">
        <option value="">All</option>
    </select>

    Location: <input type="text" asp-for="SearchString"/>
    <input type="submit" value="Filter"/>
</p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Email
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Complaints[0].ComplaintName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Complaints[0].LocationComplaint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Complaints[0].DescriptionComplaint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Complaints[0].Path)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Complaints) {
 
        <tr>
        
             <td>
               @Html.DisplayFor(model => model.user.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ComplaintName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationComplaint)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionComplaint)
            </td>
            <td>
                 <img src="~/images/@item.Path"   
                        
                         height="100" width="100"   
                         asp-append-version="true" />  

            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
            
        </tr>
}
    </tbody>
</table>